/**
 * resort-sources.js
 *
 * Authoritative mapping: resort ID -> external data source identifiers.
 * Generated by scripts/merge-sources.mjs -- do not edit by hand.
 * To update: run the lookup scripts and re-run merge-sources.mjs.
 * Last generated: 2026-05-03T18:10:46.735Z
 *
 * nwsStationId:  4-letter ICAO station code for NWS observation data
 * nwsConfidence: high/medium/low -- how closely the station matches summit elevation
 * snotelTriplet: USDA AWDB triplet e.g. "1125:UT:SNTL" -- western resorts only
 * liftieSlug:    liftie.info resort slug for lift/trail status -- null if not listed
 */

const RESORT_SOURCES = {
  'mohawk-mountain': {
    nwsStationId:  "KBDL",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 26mi away, 875ft elev delta
    // Liftie match: not_fetched
  },
  'mount-southington-ski-area': {
    nwsStationId:  "KMMK",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.1mi away, 423ft elev delta
    // Liftie match: not_fetched
  },
  'powder-ridge-park': {
    nwsStationId:  "KMMK",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 4.5mi away, 618ft elev delta
    // Liftie match: not_fetched
  },
  'ski-sundown': {
    nwsStationId:  "KBDL",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 14.1mi away, 901ft elev delta
    // Liftie match: not_fetched
  },
  'woodbury-ski-area': {
    nwsStationId:  "KOXC",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.7mi away, 5ft elev delta
    // Liftie match: not_fetched
  },
  'berkshire-east': {
    nwsStationId:  "KORE",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.7mi away, 1080ft elev delta
    // Liftie match: not_fetched
  },
  'blandford-ski-area': {
    nwsStationId:  "KBAF",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.5mi away, 1416ft elev delta
    // Liftie match: not_fetched
  },
  'blue-hills-ski-area': {
    nwsStationId:  "KOWD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3.3mi away, 586ft elev delta
    // Liftie match: not_fetched
  },
  'bousquet-ski-area': {
    nwsStationId:  "KPSF",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 0.9mi away, 727ft elev delta
    // Liftie match: not_fetched
  },
  'bradford-ski-area': {
    nwsStationId:  "KLWM",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 4.2mi away, 1413ft elev delta
    // Liftie match: not_fetched
  },
  'jiminy-peak': {
    nwsStationId:  "KPSF",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "jiminy-peak",
    // NWS: 8.1mi away, 1232ft elev delta
    // Liftie match: not_fetched
  },
  'nashoba-valley': {
    nwsStationId:  "KBED",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.2mi away, 308ft elev delta
    // Liftie match: not_fetched
  },
  'otis-ridge-ski-area': {
    nwsStationId:  "KPSF",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.7mi away, 552ft elev delta
    // Liftie match: not_fetched
  },
  'ski-butternut': {
    nwsStationId:  "KPSF",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.9mi away, 652ft elev delta
    // Liftie match: not_fetched
  },
  'ski-ward': {
    nwsStationId:  "KORH",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10mi away, 587ft elev delta
    // Liftie match: not_fetched
  },
  'wachusett-mountain-ski-area': {
    nwsStationId:  "KFIT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.5mi away, 1658ft elev delta
    // Liftie match: not_fetched
  },
  'big-squaw-mountain-ski-resort': {
    nwsStationId:  "KGNR",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.7mi away, 1806ft elev delta
    // Liftie match: not_fetched
  },
  'black-mountain-of-maine': {
    nwsStationId:  "KBML",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 31.7mi away, 1302ft elev delta
    // Liftie match: not_fetched
  },
  'camden-snow-bowl': {
    nwsStationId:  "KRKD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.5mi away, 1024ft elev delta
    // Liftie match: not_fetched
  },
  'lost-valley': {
    nwsStationId:  "KPWM",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 5.8mi away, 206ft elev delta
    // Liftie match: not_fetched
  },
  'mt-abram-ski-resort': {
    nwsStationId:  "KBML",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 26.9mi away, 1092ft elev delta
    // Liftie match: not_fetched
  },
  'mt-jefferson': {
    nwsStationId:  "KMLT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 28.4mi away, 346ft elev delta
    // Liftie match: not_fetched
  },
  'new-hermon-mountain': {
    nwsStationId:  "KBGR",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.9mi away, 260ft elev delta
    // Liftie match: not_fetched
  },
  'saddleback-inc': {
    nwsStationId:  "K8B0",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 5.5mi away, 2312ft elev delta
    // Liftie match: not_fetched
  },
  'shawnee-peak': {
    nwsStationId:  "KIZG",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 8.3mi away, 1451ft elev delta
    // Liftie match: not_fetched
  },
  'sugarloaf': {
    nwsStationId:  "K8B0",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 17.3mi away, 2429ft elev delta
    // Liftie match: not_fetched
  },
  'sunday-river': {
    nwsStationId:  "KPWM",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "sunday-river",
    // NWS: 18mi away, 1992ft elev delta
    // Liftie match: not_fetched
  },
  'attitash': {
    nwsStationId:  "KIZG",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.3mi away, 1901ft elev delta
    // Liftie match: not_fetched
  },
  'black-mountain': {
    nwsStationId:  "KIZG",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.2mi away, 1901ft elev delta
    // Liftie match: not_fetched
  },
  'bretton-woods': {
    nwsStationId:  "KHIE",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.3mi away, 2053ft elev delta
    // Liftie match: not_fetched
  },
  'cannon-mountain': {
    nwsStationId:  "KLEB",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "cannon",
    // NWS: 16.2mi away, 3033ft elev delta
    // Liftie match: not_fetched
  },
  'cranmore-mountain-resort': {
    nwsStationId:  "KLEB",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "cranmore",
    // NWS: 8.8mi away, 1551ft elev delta
    // Liftie match: not_fetched
  },
  'crotched-mountain': {
    nwsStationId:  "KAFN",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 14.7mi away, 1056ft elev delta
    // Liftie match: not_fetched
  },
  'dartmouth-skiway': {
    nwsStationId:  "KLEB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.1mi away, 1385ft elev delta
    // Liftie match: not_fetched
  },
  'granite-gorge': {
    nwsStationId:  "KEEN",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 5.6mi away, 836ft elev delta
    // Liftie match: not_fetched
  },
  'gunstock': {
    nwsStationId:  "KLCI",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3.2mi away, 1755ft elev delta
    // Liftie match: not_fetched
  },
  'king-pine': {
    nwsStationId:  "KIZG",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.8mi away, 401ft elev delta
    // Liftie match: not_fetched
  },
  'loon-mountain': {
    nwsStationId:  "KHIE",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 23.1mi away, 2003ft elev delta
    // Liftie match: not_fetched
  },
  'mcintyre-ski-area': {
    nwsStationId:  "KMHT",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 5.3mi away, 277ft elev delta
    // Liftie match: not_fetched
  },
  'mount-sunapee': {
    nwsStationId:  "KVSF",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 22.2mi away, 2169ft elev delta
    // Liftie match: not_fetched
  },
  'pats-peak': {
    nwsStationId:  "KCON",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.1mi away, 1122ft elev delta
    // Liftie match: not_fetched
  },
  'ragged-mountain-resort': {
    nwsStationId:  "KLCI",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 21.8mi away, 1705ft elev delta
    // Liftie match: not_fetched
  },
  'tenney-mountain': {
    nwsStationId:  "KLCI",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 24.2mi away, 1705ft elev delta
    // Liftie match: not_fetched
  },
  'waterville-valley': {
    nwsStationId:  "KLCI",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 26.8mi away, 3459ft elev delta
    // Liftie match: not_fetched
  },
  'whaleback-mountain': {
    nwsStationId:  "KLEB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.5mi away, 1242ft elev delta
    // Liftie match: not_fetched
  },
  'wildcat-mountain': {
    nwsStationId:  "KLEB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "wildcat",
    // NWS: 18.8mi away, 3015ft elev delta
    // Liftie match: not_fetched
  },
  'campgaw-mountain': {
    nwsStationId:  "KCDW",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13mi away, 555ft elev delta
    // Liftie match: not_fetched
  },
  'mountain-creek-resort': {
    nwsStationId:  "KCDW",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "mountain-creek",
    // NWS: 6.3mi away, 1070ft elev delta
    // Liftie match: not_fetched
  },
  'belleayre': {
    nwsStationId:  "KMSV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 33.5mi away, 2025ft elev delta
    // Liftie match: not_fetched
  },
  'brantling-ski-slopes': {
    nwsStationId:  "KSDC",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.4mi away, 426ft elev delta
    // Liftie match: not_fetched
  },
  'bristol-mountain': {
    nwsStationId:  "KROC",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 11.9mi away, 1386ft elev delta
    // Liftie match: not_fetched
  },
  'buffalo-ski-club-ski-area': {
    nwsStationId:  "KBUF",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18mi away, 2720ft elev delta
    // Liftie match: not_fetched
  },
  'catamount-ski-ride-area': {
    nwsStationId:  "KSLK",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.9mi away, 337ft elev delta
    // Liftie match: not_fetched
  },
  'dry-hill-ski-area': {
    nwsStationId:  "KART",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.3mi away, 625ft elev delta
    // Liftie match: not_fetched
  },
  'gore-mountain': {
    nwsStationId:  "KSLK",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "gore",
    // NWS: 30.3mi away, 3272ft elev delta
    // Liftie match: not_fetched
  },
  'greek-peak': {
    nwsStationId:  "KN03",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.5mi away, 902ft elev delta
    // Liftie match: not_fetched
  },
  'hickory-ski-center': {
    nwsStationId:  "KGFL",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.9mi away, 1572ft elev delta
    // Liftie match: not_fetched
  },
  'holimont-ski-area': {
    nwsStationId:  "KOLE",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.4mi away, 125ft elev delta
    // Liftie match: not_fetched
  },
  'holiday-mountain': {
    nwsStationId:  "KMSV",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.7mi away, 146ft elev delta
    // Liftie match: not_fetched
  },
  'holiday-valley': {
    nwsStationId:  "KJHW",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "holiday-valley",
    // NWS: 15.5mi away, 115ft elev delta
    // Liftie match: not_fetched
  },
  'hunt-hollow-ski-club': {
    nwsStationId:  "KDSV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.1mi away, 1371ft elev delta
    // Liftie match: not_fetched
  },
  'hunter-mountain': {
    nwsStationId:  "KMGJ",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "hunter",
    // NWS: 42mi away, 3036ft elev delta
    // Liftie match: not_fetched
  },
  'kissing-bridge': {
    nwsStationId:  "KBUF",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 23.4mi away, 991ft elev delta
    // Liftie match: not_fetched
  },
  'labrador-mt': {
    nwsStationId:  "KN03",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.9mi away, 627ft elev delta
    // Liftie match: not_fetched
  },
  'maple-ski-ridge': {
    nwsStationId:  "KALB",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.8mi away, 915ft elev delta
    // Liftie match: not_fetched
  },
  'mccauley-mountain-ski-center': {
    nwsStationId:  "KRME",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 38.7mi away, 1745ft elev delta
    // Liftie match: not_fetched
  },
  'mount-peter-ski-area': {
    nwsStationId:  "KMGJ",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.1mi away, 886ft elev delta
    // Liftie match: not_fetched
  },
  'oak-mountain': {
    nwsStationId:  "KGFL",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 39.6mi away, 2072ft elev delta
    // Liftie match: not_fetched
  },
  'peekn-peak': {
    nwsStationId:  "KJHW",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 24.8mi away, 78ft elev delta
    // Liftie match: not_fetched
  },
  'plattekill-mountain': {
    nwsStationId:  "KPOU",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 34.8mi away, 3336ft elev delta
    // Liftie match: not_fetched
  },
  'royal-mountain-ski-area': {
    nwsStationId:  "KALB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 42.5mi away, 1515ft elev delta
    // Liftie match: not_fetched
  },
  'snow-ridge': {
    nwsStationId:  "KPOU",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 30mi away, 1836ft elev delta
    // Liftie match: not_fetched
  },
  'song-mountain': {
    nwsStationId:  "KN03",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.9mi away, 742ft elev delta
    // Liftie match: not_fetched
  },
  'swain': {
    nwsStationId:  "KDSV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.5mi away, 1311ft elev delta
    // Liftie match: not_fetched
  },
  'thunder-ridge': {
    nwsStationId:  "KDXR",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.8mi away, 814ft elev delta
    // Liftie match: not_fetched
  },
  'titus-mountain': {
    nwsStationId:  "KSLK",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 25.8mi away, 362ft elev delta
    // Liftie match: not_fetched
  },
  'toggenburg-mountain': {
    nwsStationId:  "KVGC",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 20.2mi away, 863ft elev delta
    // Liftie match: not_fetched
  },
  'west-mountain': {
    nwsStationId:  "KSLK",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 21.1mi away, 193ft elev delta
    // Liftie match: not_fetched
  },
  'whiteface-mountain-resort': {
    nwsStationId:  "KSLK",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 11.6mi away, 2987ft elev delta
    // Liftie match: not_fetched
  },
  'willard-mountain': {
    nwsStationId:  "KDDH",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.1mi away, 588ft elev delta
    // Liftie match: not_fetched
  },
  'windham-mountain': {
    nwsStationId:  "KMGJ",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "windham",
    // NWS: 39mi away, 2815ft elev delta
    // Liftie match: not_fetched
  },
  'woods-valley-ski-area': {
    nwsStationId:  "KRME",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 4.9mi away, 895ft elev delta
    // Liftie match: not_fetched
  },
  'bear-creek-mountain-resort': {
    nwsStationId:  "KUKT",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.2mi away, 591ft elev delta
    // Liftie match: not_fetched
  },
  'big-boulder': {
    nwsStationId:  "KMPO",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 14.3mi away, 289ft elev delta
    // Liftie match: not_fetched
  },
  'blue-knob': {
    nwsStationId:  "KAOO",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.9mi away, 1679ft elev delta
    // Liftie match: not_fetched
  },
  'blue-mountain-ski-area': {
    nwsStationId:  "KABE",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.4mi away, 1216ft elev delta
    // Liftie match: not_fetched
  },
  'camelback-mountain-resort': {
    nwsStationId:  "KAVP",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "camelback",
    // NWS: 6.1mi away, 214ft elev delta
    // Liftie match: not_fetched
  },
  'eagle-rock': {
    nwsStationId:  "KMPO",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 4.5mi away, 76ft elev delta
    // Liftie match: not_fetched
  },
  'elk-mountain-ski-resort': {
    nwsStationId:  "KBFD",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "elk-mountain",
    // NWS: 27.8mi away, 1732ft elev delta
    // Liftie match: not_fetched
  },
  'jack-frost': {
    nwsStationId:  "KMPO",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 14.3mi away, 114ft elev delta
    // Liftie match: not_fetched
  },
  'liberty': {
    nwsStationId:  "KN38",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 19.1mi away, 702ft elev delta
    // Liftie match: not_fetched
  },
  'montage-mountain': {
    nwsStationId:  "KAVP",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.2mi away, 999ft elev delta
    // Liftie match: not_fetched
  },
  'mount-pleasant-of-edinboro': {
    nwsStationId:  "KERI",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.8mi away, 808ft elev delta
    // Liftie match: not_fetched
  },
  'roundtop-mountain-resort': {
    nwsStationId:  "KCXY",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 8.4mi away, 1065ft elev delta
    // Liftie match: not_fetched
  },
  'seven-springs': {
    nwsStationId:  "K2G9",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15mi away, 719ft elev delta
    // Liftie match: not_fetched
  },
  'shawnee-mountain-ski-area': {
    nwsStationId:  "KMPO",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.8mi away, 536ft elev delta
    // Liftie match: not_fetched
  },
  'ski-big-bear': {
    nwsStationId:  "KMSV",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.8mi away, 154ft elev delta
    // Liftie match: not_fetched
  },
  'big-bear': {
    nwsStationId:  "KMSV",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.9mi away, 204ft elev delta
    // Liftie match: not_fetched
  },
  'ski-sawmill': {
    nwsStationId:  "KN38",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.5mi away, 323ft elev delta
    // Liftie match: not_fetched
  },
  'sno-mountain': {
    nwsStationId:  "KAVP",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3.4mi away, 239ft elev delta
    // Liftie match: not_fetched
  },
  'spring-mountain-ski-area': {
    nwsStationId:  "KPTW",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6mi away, 240ft elev delta
    // Liftie match: not_fetched
  },
  'tussey-mountain': {
    nwsStationId:  "KAOO",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.3mi away, 283ft elev delta
    // Liftie match: not_fetched
  },
  'whitetail-resort': {
    nwsStationId:  "KHGR",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 11.1mi away, 1098ft elev delta
    // Liftie match: not_fetched
  },
  'yawgoo-valley': {
    nwsStationId:  "KOQU",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 8.1mi away, 295ft elev delta
    // Liftie match: not_fetched
  },
  'bolton-valley': {
    nwsStationId:  "KMVL",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 14mi away, 2441ft elev delta
    // Liftie match: not_fetched
  },
  'bromley-mountain': {
    nwsStationId:  "KRUT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "bromley",
    // NWS: 21.1mi away, 2497ft elev delta
    // Liftie match: not_fetched
  },
  'burke-mountain': {
    nwsStationId:  "KBTV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "burke",
    // NWS: 6.2mi away, 2079ft elev delta
    // Liftie match: not_fetched
  },
  'jay-peak': {
    nwsStationId:  "KEFK",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.6mi away, 3034ft elev delta
    // Liftie match: not_fetched
  },
  'killington-resort': {
    nwsStationId:  "KRUT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "killington",
    // NWS: 9.5mi away, 3454ft elev delta
    // Liftie match: not_fetched
  },
  'mad-river-glen': {
    nwsStationId:  "KMPV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "mad-river-glen",
    // NWS: 17.4mi away, 2472ft elev delta
    // Liftie match: not_fetched
  },
  'magic-mountain': {
    nwsStationId:  "KVSF",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.9mi away, 2276ft elev delta
    // Liftie match: not_fetched
  },
  'middlebury-snow-bowl': {
    nwsStationId:  "KBTV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 27.8mi away, 1455ft elev delta
    // Liftie match: not_fetched
  },
  'mount-snow': {
    nwsStationId:  "KDDH",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.9mi away, 2773ft elev delta
    // Liftie match: not_fetched
  },
  'okemo-mountain-resort': {
    nwsStationId:  "KRUT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "okemo",
    // NWS: 10.6mi away, 2770ft elev delta
    // Liftie match: not_fetched
  },
  'pico-mountain-at-killington': {
    nwsStationId:  "KRUT",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.8mi away, 3180ft elev delta
    // Liftie match: not_fetched
  },
  'suicide-six': {
    nwsStationId:  "KLEB",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.2mi away, 642ft elev delta
    // Liftie match: not_fetched
  },
  'smugglers-notch-resort': {
    nwsStationId:  "KBTV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "smugglers-notch",
    // NWS: 9.3mi away, 2931ft elev delta
    // Liftie match: not_fetched
  },
  'stowe-mountain-resort': {
    nwsStationId:  "KMVL",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "stowe",
    // NWS: 8mi away, 3686ft elev delta
    // Liftie match: not_fetched
  },
  'stratton-mountain': {
    nwsStationId:  "KDDH",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 23mi away, 3048ft elev delta
    // Liftie match: not_fetched
  },
  'sugarbush': {
    nwsStationId:  "KMPV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.9mi away, 2918ft elev delta
    // Liftie match: not_fetched
  },
  'wisp-resort': {
    nwsStationId:  "KCKB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "wisp",
    // NWS: 6.2mi away, 139ft elev delta
    // Liftie match: not_fetched
  },
  'wintergreen-resort': {
    nwsStationId:  "KCHO",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "wintergreen",
    // NWS: 12.2mi away, 2078ft elev delta
    // Liftie match: not_fetched
  },
  'massanutten-resort': {
    nwsStationId:  "KSHD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "massanutten",
    // NWS: 12.2mi away, 1890ft elev delta
    // Liftie match: not_fetched
  },
  'bryce-resort': {
    nwsStationId:  "KSHD",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 12.7mi away, 775ft elev delta
    // Liftie match: not_fetched
  },
  'the-homestead': {
    nwsStationId:  "KHLX",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 2.7mi away, 593ft elev delta
    // Liftie match: not_fetched
  },
  'snowshoe-mountain': {
    nwsStationId:  "KLWB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    "snowshoe",
    // NWS: 34.5mi away, 2863ft elev delta
    // Liftie match: not_fetched
  },
  'canaan-valley-resort': {
    nwsStationId:  "K2G4",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 40.6mi away, 1347ft elev delta
    // Liftie match: not_fetched
  },
  'timberline-wv': {
    nwsStationId:  "K2G4",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 35.9mi away, 1335ft elev delta
    // Liftie match: not_fetched
  },
  'winterplace': {
    nwsStationId:  "KI16",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.4mi away, 1815ft elev delta
    // Liftie match: not_fetched
  },
  'sugar-mountain': {
    nwsStationId:  "KTNB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.4mi away, 2154ft elev delta
    // Liftie match: not_fetched
  },
  'beech-mountain': {
    nwsStationId:  "KTNB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.2mi away, 2360ft elev delta
    // Liftie match: not_fetched
  },
  'appalachian-ski-mountain': {
    nwsStationId:  "KBKV",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 2.1mi away, 544ft elev delta
    // Liftie match: not_fetched
  },
  'cataloochee-ski-area': {
    nwsStationId:  "KAVL",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.2mi away, 2543ft elev delta
    // Liftie match: not_fetched
  },
  'wolf-ridge-ski-resort': {
    nwsStationId:  "KAVL",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 24.1mi away, 2535ft elev delta
    // Liftie match: not_fetched
  },
  'ober-gatlinburg': {
    nwsStationId:  "KTYS",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.4mi away, 2899ft elev delta
    // Liftie match: not_fetched
  },
  'boyne-highlands': {
    nwsStationId:  "KPLN",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "boyne-highlands",
    // NWS: 1.6mi away, 635ft elev delta
    // Liftie match: not_fetched
  },
  'boyne-mountain': {
    nwsStationId:  "KPLN",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "boyne-mountain",
    // NWS: 0.2mi away, 400ft elev delta
    // Liftie match: not_fetched
  },
  'crystal-mountain-mi': {
    nwsStationId:  "KTVC",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "crystal-mountain",
    // NWS: 18.4mi away, 531ft elev delta
    // Liftie match: not_fetched
  },
  'nubs-nob': {
    nwsStationId:  "KPLN",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "nubs-nob",
    // NWS: 3.3mi away, 415ft elev delta
    // Liftie match: not_fetched
  },
  'mt-bohemia': {
    nwsStationId:  "KCMX",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.1mi away, 540ft elev delta
    // Liftie match: not_fetched
  },
  'shanty-creek': {
    nwsStationId:  "KACB",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3.4mi away, 537ft elev delta
    // Liftie match: not_fetched
  },
  'big-powderhorn': {
    nwsStationId:  "KIWD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 1.8mi away, 542ft elev delta
    // Liftie match: not_fetched
  },
  'ski-brule': {
    nwsStationId:  "KIWD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 26.6mi away, 194ft elev delta
    // Liftie match: not_fetched
  },
  'indianhead-mountain': {
    nwsStationId:  "KIWD",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 0.4mi away, 508ft elev delta
    // Liftie match: not_fetched
  },
  'blackjack-ski-resort': {
    nwsStationId:  "KIWD",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 1.6mi away, 735ft elev delta
    // Liftie match: not_fetched
  },
  'pine-knob-ski-resort': {
    nwsStationId:  "KDET",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "pine-knob",
    // NWS: 4.1mi away, 198ft elev delta
    // Liftie match: not_fetched
  },
  'alpine-valley-mi': {
    nwsStationId:  "KDET",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "alpine-valley",
    // NWS: 8.8mi away, 269ft elev delta
    // Liftie match: not_fetched
  },
  'mount-holiday-ski-area': {
    nwsStationId:  "KTVC",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 4.4mi away, 486ft elev delta
    // Liftie match: not_fetched
  },
  'granite-peak-wi': {
    nwsStationId:  "KCWA",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    "granite-peak",
    // NWS: 1.8mi away, 750ft elev delta
    // Liftie match: not_fetched
  },
  'devils-head-resort': {
    nwsStationId:  "KMSN",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "devils-head",
    // NWS: 6.8mi away, 429ft elev delta
    // Liftie match: not_fetched
  },
  'cascade-mountain-wi': {
    nwsStationId:  "KMSN",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    "cascade-mountain",
    // NWS: 8mi away, 339ft elev delta
    // Liftie match: not_fetched
  },
  'whitecap-mountains': {
    nwsStationId:  "KRHI",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 20.1mi away, 670ft elev delta
    // Liftie match: not_fetched
  },
  'mount-la-crosse': {
    nwsStationId:  "KLSE",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.3mi away, 663ft elev delta
    // Liftie match: not_fetched
  },
  'trollhaugen': {
    nwsStationId:  "KOEO",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 2.6mi away, 334ft elev delta
    // Liftie match: not_fetched
  },
  'lutsen-mountains': {
    nwsStationId:  "KGNA",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 18.1mi away, 1078ft elev delta
    // Liftie match: not_fetched
  },
  'spirit-mountain': {
    nwsStationId:  "KSUW",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 6.9mi away, 651ft elev delta
    // Liftie match: not_fetched
  },
  'afton-alps': {
    nwsStationId:  "KSGS",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.7mi away, 268ft elev delta
    // Liftie match: not_fetched
  },
  'welch-village': {
    nwsStationId:  "KRGK",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.6mi away, 279ft elev delta
    // Liftie match: not_fetched
  },
  'buck-hill-mn': {
    nwsStationId:  "KFCM",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 7.5mi away, 394ft elev delta
    // Liftie match: not_fetched
  },
  'wild-mountain-mn': {
    nwsStationId:  "KOEO",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.9mi away, 274ft elev delta
    // Liftie match: not_fetched
  },
  'mad-river-mountain': {
    nwsStationId:  "KI95",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 13.1mi away, 431ft elev delta
    // Liftie match: not_fetched
  },
  'boston-mills-brandywine': {
    nwsStationId:  "KAKR",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.4mi away, 4ft elev delta
    // Liftie match: not_fetched
  },
  'snow-trails': {
    nwsStationId:  "KMFD",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 15.6mi away, 34ft elev delta
    // Liftie match: not_fetched
  },
  'alpine-valley-oh': {
    nwsStationId:  "KBKL",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 22.2mi away, 646ft elev delta
    // Liftie match: not_fetched
  },
  'paoli-peaks': {
    nwsStationId:  "KHNB",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 34.1mi away, 422ft elev delta
    // Liftie match: not_fetched
  },
  'chestnut-mountain-il': {
    nwsStationId:  "KDBQ",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 16.8mi away, 30ft elev delta
    // Liftie match: not_fetched
  },
  'sundown-mountain-ia': {
    nwsStationId:  "KDBQ",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 17.1mi away, 252ft elev delta
    // Liftie match: not_fetched
  },
  'hidden-valley-mo': {
    nwsStationId:  "KSUS",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10.1mi away, 317ft elev delta
    // Liftie match: not_fetched
  },
  'snow-creek-mo': {
    nwsStationId:  "KSTJ",
    nwsConfidence: "high",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 10mi away, 377ft elev delta
    // Liftie match: not_fetched
  },
  'vail': {
    nwsStationId:  "G3823",
    nwsConfidence: "low",
    snotelTriplet: "842:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1.2mi away, 3420ft elev delta
    // SNOTEL: 1.8mi away
    // Liftie match: not_fetched
  },
  'breckenridge': {
    nwsStationId:  "KCCU",
    nwsConfidence: "medium",
    snotelTriplet: "09046000:CO:USGS",
    liftieSlug:    null,
    // NWS: 6.1mi away, 970ft elev delta
    // SNOTEL: 6.2mi away
    // Liftie match: not_fetched
  },
  'keystone-resort': {
    nwsStationId:  "KBKF",
    nwsConfidence: "low",
    snotelTriplet: "384:CO:SNTL",
    liftieSlug:    "keystone",
    // NWS: 13.5mi away, 48ft elev delta
    // SNOTEL: 9.3mi away
    // Liftie match: not_fetched
  },
  'beaver-creek': {
    nwsStationId:  "CO092",
    nwsConfidence: "low",
    snotelTriplet: "842:CO:SNTL",
    liftieSlug:    null,
    // NWS: 3.6mi away, 3664ft elev delta
    // SNOTEL: 7.3mi away
    // Liftie match: not_fetched
  },
  'arapahoe-basin': {
    nwsStationId:  "KBKF",
    nwsConfidence: "low",
    snotelTriplet: "384:CO:SNTL",
    liftieSlug:    "a-basin",
    // NWS: 18.9mi away, 1022ft elev delta
    // SNOTEL: 4.5mi away
    // Liftie match: not_fetched
  },
  'copper-mountain-co': {
    nwsStationId:  "KCCU",
    nwsConfidence: "high",
    snotelTriplet: "531:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1.9mi away, 285ft elev delta
    // SNOTEL: 11mi away
    // Liftie match: not_fetched
  },
  'winter-park-resort': {
    nwsStationId:  "KBKF",
    nwsConfidence: "low",
    snotelTriplet: "551:CO:SNTL",
    liftieSlug:    "winter-park",
    // NWS: 16.2mi away, 3853ft elev delta
    // SNOTEL: 5.8mi away
    // Liftie match: not_fetched
  },
  'steamboat-resort': {
    nwsStationId:  "CO102",
    nwsConfidence: "low",
    snotelTriplet: "825:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1mi away, 3786ft elev delta
    // SNOTEL: 8.7mi away
    // Liftie match: not_fetched
  },
  'aspen-snowmass': {
    nwsStationId:  "KASE",
    nwsConfidence: "medium",
    snotelTriplet: "1050:CO:SNTL",
    liftieSlug:    "aspen",
    // NWS: 4.4mi away, 4837ft elev delta
    // SNOTEL: 15.5mi away
    // Liftie match: not_fetched
  },
  'aspen-mountain': {
    nwsStationId:  "KASE",
    nwsConfidence: "medium",
    snotelTriplet: "1050:CO:SNTL",
    liftieSlug:    "ajax",
    // NWS: 1.1mi away, 3276ft elev delta
    // SNOTEL: 12.9mi away
    // Liftie match: not_fetched
  },
  'aspen-highlands': {
    nwsStationId:  "CO100",
    nwsConfidence: "low",
    snotelTriplet: "1326:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1.9mi away, 3739ft elev delta
    // SNOTEL: 12.8mi away
    // Liftie match: not_fetched
  },
  'buttermilk-co': {
    nwsStationId:  "KASE",
    nwsConfidence: "low",
    snotelTriplet: "CO0016:CO:USGS",
    liftieSlug:    null,
    // NWS: 2.2mi away, 2227ft elev delta
    // SNOTEL: 10mi away
    // Liftie match: not_fetched
  },
  'telluride': {
    nwsStationId:  "KTEX",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3.2mi away, 4072ft elev delta
    // Liftie match: not_fetched
  },
  'crested-butte': {
    nwsStationId:  "CO100",
    nwsConfidence: "low",
    snotelTriplet: "1326:CO:SNTL",
    liftieSlug:    null,
    // NWS: 21.7mi away, 4226ft elev delta
    // SNOTEL: 10mi away
    // Liftie match: not_fetched
  },
  'purgatory-resort': {
    nwsStationId:  "KDRO",
    nwsConfidence: "low",
    snotelTriplet: "589:CO:SNTL",
    liftieSlug:    "purgatory",
    // NWS: 11.8mi away, 481ft elev delta
    // SNOTEL: 6.5mi away
    // Liftie match: not_fetched
  },
  'wolf-creek-ski-area': {
    nwsStationId:  "KALS",
    nwsConfidence: "low",
    snotelTriplet: "780:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1.8mi away, 145ft elev delta
    // SNOTEL: 9.8mi away
    // Liftie match: not_fetched
  },
  'monarch-mountain': {
    nwsStationId:  "KGUC",
    nwsConfidence: "low",
    snotelTriplet: "580:CO:SNTL",
    liftieSlug:    null,
    // NWS: 1.4mi away, 59ft elev delta
    // SNOTEL: 2mi away
    // Liftie match: not_fetched
  },
  'eldora-mountain': {
    nwsStationId:  "KBDU",
    nwsConfidence: "low",
    snotelTriplet: "838:CO:SNTL",
    liftieSlug:    null,
    // NWS: 20.3mi away, 5512ft elev delta
    // SNOTEL: 6.7mi away
    // Liftie match: not_fetched
  },
  'loveland-ski-area': {
    nwsStationId:  "KBKF",
    nwsConfidence: "low",
    snotelTriplet: "415:CO:SNTL",
    liftieSlug:    "loveland",
    // NWS: 19.5mi away, 982ft elev delta
    // SNOTEL: 6.9mi away
    // Liftie match: not_fetched
  },
  'ski-cooper': {
    nwsStationId:  "KEGE",
    nwsConfidence: "low",
    snotelTriplet: "415:CO:SNTL",
    liftieSlug:    null,
    // NWS: 15.1mi away, 1451ft elev delta
    // SNOTEL: 3.4mi away
    // Liftie match: not_fetched
  },
  'sunlight-mountain-resort': {
    nwsStationId:  "CO090",
    nwsConfidence: "low",
    snotelTriplet: "345:CO:SNTL",
    liftieSlug:    null,
    // NWS: 6.5mi away, 3714ft elev delta
    // SNOTEL: 17.5mi away
    // Liftie match: not_fetched
  },
  'powderhorn-resort': {
    nwsStationId:  "CAGMS",
    nwsConfidence: "high",
    snotelTriplet: "622:CO:SNTL",
    liftieSlug:    null,
    // NWS: 3.4mi away, 472ft elev delta
    // SNOTEL: 3.6mi away
    // Liftie match: not_fetched
  },
  'howelsen-hill': {
    nwsStationId:  "CO102",
    nwsConfidence: "high",
    snotelTriplet: "7936:CO:COOP",
    liftieSlug:    null,
    // NWS: 1.7mi away, 354ft elev delta
    // SNOTEL: 0.6mi away
    // Liftie match: not_fetched
  },
  'park-city-mountain': {
    nwsStationId:  "UT224",
    nwsConfidence: "low",
    snotelTriplet: "814:UT:SNTL",
    liftieSlug:    null,
    // NWS: 1.8mi away, 3329ft elev delta
    // SNOTEL: 2.4mi away
    // Liftie match: not_fetched
  },
  'deer-valley-resort': {
    nwsStationId:  "KSLC",
    nwsConfidence: "low",
    snotelTriplet: "1115:UT:SNTL",
    liftieSlug:    "deer-valley",
    // NWS: 3.5mi away, 2873ft elev delta
    // SNOTEL: 3mi away
    // Liftie match: not_fetched
  },
  'snowbird': {
    nwsStationId:  "KSLC",
    nwsConfidence: "low",
    snotelTriplet: "1125:UT:SNTL",
    liftieSlug:    "snowbird",
    // NWS: 9.5mi away, 4303ft elev delta
    // Liftie match: not_fetched
  },
  'alta-ski-area': {
    nwsStationId:  "KSLC",
    nwsConfidence: "low",
    snotelTriplet: "1025:UT:SNTL",
    liftieSlug:    "alta",
    // NWS: 8.6mi away, 4371ft elev delta
    // Liftie match: not_fetched
  },
  'solitude-mountain-resort': {
    nwsStationId:  "KSLC",
    nwsConfidence: "low",
    snotelTriplet: "1115:UT:SNTL",
    liftieSlug:    "solitude",
    // NWS: 5.3mi away, 3338ft elev delta
    // SNOTEL: 3.1mi away
    // Liftie match: not_fetched
  },
  'brighton-resort': {
    nwsStationId:  "KSLC",
    nwsConfidence: "low",
    snotelTriplet: "1115:UT:SNTL",
    liftieSlug:    "brighton",
    // NWS: 6.3mi away, 3803ft elev delta
    // SNOTEL: 3.1mi away
    // Liftie match: not_fetched
  },
  'snowbasin-resort': {
    nwsStationId:  "KOGD",
    nwsConfidence: "medium",
    snotelTriplet: "1063:UT:SNTL",
    liftieSlug:    "snowbasin",
    // NWS: 8.4mi away, 4910ft elev delta
    // SNOTEL: 11.9mi away
    // Liftie match: not_fetched
  },
  'sundance-resort': {
    nwsStationId:  "KPVU",
    nwsConfidence: "low",
    snotelTriplet: "1023:UT:SNTL",
    liftieSlug:    null,
    // NWS: 10.1mi away, 2653ft elev delta
    // SNOTEL: 2.8mi away
    // Liftie match: not_fetched
  },
  'brian-head-resort': {
    nwsStationId:  "KCDC",
    nwsConfidence: "low",
    snotelTriplet: "1015:UT:SNTL",
    liftieSlug:    null,
    // NWS: 13.6mi away, 5726ft elev delta
    // SNOTEL: 1.1mi away
    // Liftie match: not_fetched
  },
  'beaver-mountain-ut': {
    nwsStationId:  "KLGU",
    nwsConfidence: "medium",
    snotelTriplet: "1008:UT:SNTL",
    liftieSlug:    null,
    // NWS: 20.6mi away, 4394ft elev delta
    // SNOTEL: 7.5mi away
    // Liftie match: not_fetched
  },
  'jackson-hole-mountain-resort': {
    nwsStationId:  "KJAC",
    nwsConfidence: "medium",
    snotelTriplet: "1050:WY:SNTL",
    liftieSlug:    "jackson-hole",
    // NWS: 4.8mi away, 4000ft elev delta
    // SNOTEL: 14.2mi away
    // Liftie match: not_fetched
  },
  'grand-targhee-resort': {
    nwsStationId:  "KJAC",
    nwsConfidence: "medium",
    snotelTriplet: "1042:WY:SNTL",
    liftieSlug:    "grand-targhee",
    // NWS: 16.6mi away, 3750ft elev delta
    // SNOTEL: 0.9mi away
    // Liftie match: not_fetched
  },
  'snow-king-mountain': {
    nwsStationId:  "KJAC",
    nwsConfidence: "high",
    snotelTriplet: "10F20:WY:SNOW",
    liftieSlug:    "snow-king",
    // NWS: 8.9mi away, 1358ft elev delta
    // SNOTEL: 0.9mi away
    // Liftie match: not_fetched
  },
  'big-sky-resort': {
    nwsStationId:  "KBZN",
    nwsConfidence: "low",
    snotelTriplet: "1016:MT:SNTL",
    liftieSlug:    "big-sky",
    // NWS: 3.3mi away, 3966ft elev delta
    // Liftie match: not_fetched
  },
  'whitefish-mountain-resort': {
    nwsStationId:  "KFCA",
    nwsConfidence: "medium",
    snotelTriplet: "1024:MT:SNTL",
    liftieSlug:    "whitefish",
    // NWS: 9.8mi away, 3701ft elev delta
    // SNOTEL: 0.4mi away
    // Liftie match: not_fetched
  },
  'bridger-bowl': {
    nwsStationId:  "KBZN",
    nwsConfidence: "medium",
    snotelTriplet: "1003:MT:SNTL",
    liftieSlug:    "bridger-bowl",
    // NWS: 3.9mi away, 2150ft elev delta
    // SNOTEL: 5.2mi away
    // Liftie match: not_fetched
  },
  'red-lodge-mountain': {
    nwsStationId:  "G6884",
    nwsConfidence: "low",
    snotelTriplet: "09D04:MT:SNOW",
    liftieSlug:    null,
    // NWS: 0.5mi away, 3654ft elev delta
    // SNOTEL: 11.4mi away
    // Liftie match: not_fetched
  },
  'discovery-ski-area': {
    nwsStationId:  "PHGM8",
    nwsConfidence: "low",
    snotelTriplet: "13C09:MT:SNOW",
    liftieSlug:    null,
    // NWS: 13.4mi away, 2876ft elev delta
    // SNOTEL: 8.8mi away
    // Liftie match: not_fetched
  },
  'sun-valley-resort': {
    nwsStationId:  "KSUN",
    nwsConfidence: "medium",
    snotelTriplet: "811:ID:SNTL",
    liftieSlug:    "sun-valley",
    // NWS: 13.8mi away, 3832ft elev delta
    // SNOTEL: 3.6mi away
    // Liftie match: not_fetched
  },
  'schweitzer-mountain': {
    nwsStationId:  "STZI1",
    nwsConfidence: "high",
    snotelTriplet: "738:ID:SNTL",
    liftieSlug:    null,
    // NWS: 0.9mi away, 310ft elev delta
    // SNOTEL: 0.9mi away
    // Liftie match: not_fetched
  },
  'bogus-basin': {
    nwsStationId:  "KBOI",
    nwsConfidence: "medium",
    snotelTriplet: "978:ID:SNTL",
    liftieSlug:    "bogus-basin",
    // NWS: 0.2mi away, 1250ft elev delta
    // SNOTEL: 0.2mi away
    // Liftie match: not_fetched
  },
  'brundage-mountain': {
    nwsStationId:  "KMUO",
    nwsConfidence: "low",
    snotelTriplet: "357:ID:SNTL",
    liftieSlug:    null,
    // NWS: 6.2mi away, 2620ft elev delta
    // SNOTEL: 5.3mi away
    // Liftie match: not_fetched
  },
  'tamarack-resort': {
    nwsStationId:  "KBOI",
    nwsConfidence: "low",
    snotelTriplet: "978:ID:SNTL",
    liftieSlug:    null,
    // NWS: 19.1mi away, 2680ft elev delta
    // SNOTEL: 7.3mi away
    // Liftie match: not_fetched
  },
  'silver-mountain-resort': {
    nwsStationId:  "KCOE",
    nwsConfidence: "low",
    snotelTriplet: "888:ID:SNTL",
    liftieSlug:    "silver-mountain",
    // NWS: 1.4mi away, 2300ft elev delta
    // SNOTEL: 6.3mi away
    // Liftie match: not_fetched
  },
  'taos-ski-valley': {
    nwsStationId:  "KTAOS",
    nwsConfidence: "medium",
    snotelTriplet: "892:NM:SNTL",
    liftieSlug:    "taos",
    // NWS: 14.6mi away, 3489ft elev delta
    // SNOTEL: 1.1mi away
    // Liftie match: not_fetched
  },
  'ski-santa-fe': {
    nwsStationId:  "KSAF",
    nwsConfidence: "medium",
    snotelTriplet: "879:NM:SNTL",
    liftieSlug:    "ski-santa-fe",
    // NWS: 20.5mi away, 5815ft elev delta
    // SNOTEL: 3.1mi away
    // Liftie match: not_fetched
  },
  'angel-fire-resort': {
    nwsStationId:  "KTAOS",
    nwsConfidence: "low",
    snotelTriplet: "892:NM:SNTL",
    liftieSlug:    "angel-fire",
    // SNOTEL: 7.6mi away
    // Liftie match: not_fetched
  },
  'red-river-ski-area': {
    nwsStationId:  "KTAOS",
    nwsConfidence: "low",
    snotelTriplet: "892:NM:SNTL",
    liftieSlug:    null,
    // NWS: 20.6mi away, 2020ft elev delta
    // SNOTEL: 4mi away
    // Liftie match: not_fetched
  },
  'ski-apache': {
    nwsStationId:  "KROW",
    nwsConfidence: "low",
    snotelTriplet: "879:NM:SNTL",
    liftieSlug:    null,
    // NWS: 15.8mi away, 4741ft elev delta
    // SNOTEL: 1.4mi away
    // Liftie match: not_fetched
  },
  'arizona-snowbowl': {
    nwsStationId:  "KFLG",
    nwsConfidence: "medium",
    snotelTriplet: "1241:AZ:SNTL",
    liftieSlug:    "arizona-snowbowl",
    // NWS: 1.1mi away, 644ft elev delta
    // SNOTEL: 1.3mi away
    // Liftie match: not_fetched
  },
  'sunrise-park-resort': {
    nwsStationId:  "KWSL",
    nwsConfidence: "low",
    snotelTriplet: "1008:AZ:SNTL",
    liftieSlug:    null,
    // NWS: 8.4mi away, 2760ft elev delta
    // Liftie match: not_fetched
  },
  'mount-rose-ski-tahoe': {
    nwsStationId:  "KRNO",
    nwsConfidence: "low",
    snotelTriplet: "1050:NV:SNTL",
    liftieSlug:    "mount-rose",
    // NWS: 0.7mi away, 50ft elev delta
    // SNOTEL: 2.7mi away
    // Liftie match: not_fetched
  },
  'diamond-peak': {
    nwsStationId:  "KRNO",
    nwsConfidence: "low",
    snotelTriplet: "1050:NV:SNTL",
    liftieSlug:    "diamond-peak",
    // NWS: 0.9mi away, 1985ft elev delta
    // SNOTEL: 4.7mi away
    // Liftie match: not_fetched
  },
  'lee-canyon': {
    nwsStationId:  "KLAS",
    nwsConfidence: "low",
    snotelTriplet: "1183:NV:SNTL",
    liftieSlug:    null,
    // NWS: 4.6mi away, 2170ft elev delta
    // SNOTEL: 1.3mi away
    // Liftie match: not_fetched
  },
  'palisades-tahoe': {
    nwsStationId:  "KTRK",
    nwsConfidence: "medium",
    snotelTriplet: "1050:CA:SNTL",
    liftieSlug:    "palisades-tahoe",
    // NWS: 0.4mi away, 2555ft elev delta
    // SNOTEL: 1.7mi away
    // Liftie match: not_fetched
  },
  'mammoth-mountain': {
    nwsStationId:  "KMMH",
    nwsConfidence: "medium",
    snotelTriplet: "1243:CA:SNTL",
    liftieSlug:    "mammoth",
    // NWS: 0mi away, 19ft elev delta
    // SNOTEL: 12.8mi away
    // Liftie match: not_fetched
  },
  'heavenly-mountain-resort': {
    nwsStationId:  "KTVL",
    nwsConfidence: "medium",
    snotelTriplet: "778:CA:SNTL",
    liftieSlug:    "heavenly",
    // NWS: 2.4mi away, 3804ft elev delta
    // SNOTEL: 7.4mi away
    // Liftie match: not_fetched
  },
  'northstar-california': {
    nwsStationId:  "KTRK",
    nwsConfidence: "medium",
    snotelTriplet: "1050:CA:SNTL",
    liftieSlug:    "northstar",
    // NWS: 3mi away, 2711ft elev delta
    // SNOTEL: 12.4mi away
    // Liftie match: not_fetched
  },
  'kirkwood-mountain': {
    nwsStationId:  "KTVL",
    nwsConfidence: "low",
    snotelTriplet: "778:CA:SNTL",
    liftieSlug:    "kirkwood",
    // NWS: 10.2mi away, 4560ft elev delta
    // SNOTEL: 4.4mi away
    // Liftie match: not_fetched
  },
  'sierra-at-tahoe': {
    nwsStationId:  "KTVL",
    nwsConfidence: "medium",
    snotelTriplet: "778:CA:SNTL",
    liftieSlug:    "sierra-at-tahoe",
    // NWS: 9.7mi away, 3612ft elev delta
    // SNOTEL: 3.5mi away
    // Liftie match: not_fetched
  },
  'june-mountain': {
    nwsStationId:  "SE386",
    nwsConfidence: "low",
    snotelTriplet: "GEM:CA:MSNT",
    liftieSlug:    null,
    // NWS: 1.2mi away, 2445ft elev delta
    // SNOTEL: 4.9mi away
    // Liftie match: not_fetched
  },
  'bear-mountain-ca': {
    nwsStationId:  "E3043",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 1.1mi away, 1535ft elev delta
    // Liftie match: not_fetched
  },
  'snow-summit': {
    nwsStationId:  "CVEC1",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 2.3mi away, 2582ft elev delta
    // Liftie match: not_fetched
  },
  'mountain-high-resort': {
    nwsStationId:  "E0585",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 3mi away, 2247ft elev delta
    // Liftie match: not_fetched
  },
  'dodge-ridge': {
    nwsStationId:  "STUC1",
    nwsConfidence: "low",
    snotelTriplet: "GNL:CA:SNOW",
    liftieSlug:    null,
    // NWS: 18.4mi away, 2136ft elev delta
    // SNOTEL: 3.8mi away
    // Liftie match: not_fetched
  },
  'china-peak': {
    nwsStationId:  "KSPC1",
    nwsConfidence: "high",
    snotelTriplet: "CYT:CA:SNOW",
    liftieSlug:    null,
    // NWS: 5.2mi away, 420ft elev delta
    // SNOTEL: 4.8mi away
    // Liftie match: not_fetched
  },
  'snow-valley-ca': {
    nwsStationId:  "E9931",
    nwsConfidence: "medium",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 2.4mi away, 1007ft elev delta
    // Liftie match: not_fetched
  },
  'mt-shasta-ski-park': {
    nwsStationId:  "KMHS",
    nwsConfidence: "low",
    snotelTriplet: "MSH:CA:SNOW",
    liftieSlug:    null,
    // NWS: 5.8mi away, 4360ft elev delta
    // SNOTEL: 4.1mi away
    // Liftie match: not_fetched
  },
  'homewood-mountain-resort': {
    nwsStationId:  "KTRK",
    nwsConfidence: "medium",
    snotelTriplet: "1050:CA:SNTL",
    liftieSlug:    null,
    // NWS: 0.7mi away, 759ft elev delta
    // SNOTEL: 5.7mi away
    // Liftie match: not_fetched
  },
  'mt-hood-meadows': {
    nwsStationId:  "KPDX",
    nwsConfidence: "low",
    snotelTriplet: "650:OR:SNTL",
    liftieSlug:    "mt-hood-meadows",
    // NWS: 0.2mi away, 1920ft elev delta
    // SNOTEL: 7.1mi away
    // Liftie match: not_fetched
  },
  'mt-bachelor': {
    nwsStationId:  "KRDM",
    nwsConfidence: "medium",
    snotelTriplet: "548:OR:SNTL",
    liftieSlug:    "mt-bachelor",
    // NWS: 23.6mi away, 5897ft elev delta
    // Liftie match: not_fetched
  },
  'timberline-lodge': {
    nwsStationId:  "KPDX",
    nwsConfidence: "low",
    snotelTriplet: "650:OR:SNTL",
    liftieSlug:    "timberline",
    // NWS: 0.1mi away, 2740ft elev delta
    // Liftie match: not_fetched
  },
  'mt-hood-skibowl': {
    nwsStationId:  "KPDX",
    nwsConfidence: "low",
    snotelTriplet: "650:OR:SNTL",
    liftieSlug:    "skibowl",
    // NWS: 0.5mi away, 16ft elev delta
    // SNOTEL: 4.4mi away
    // Liftie match: not_fetched
  },
  'hoodoo-ski-area': {
    nwsStationId:  "PEFO3",
    nwsConfidence: "low",
    snotelTriplet: "526:OR:SNTL",
    liftieSlug:    null,
    // NWS: 13.2mi away, 2246ft elev delta
    // SNOTEL: 1.4mi away
    // Liftie match: not_fetched
  },
  'willamette-pass': {
    nwsStationId:  "EMFO3",
    nwsConfidence: "low",
    snotelTriplet: "801:OR:SNTL",
    liftieSlug:    null,
    // NWS: 11.9mi away, 2893ft elev delta
    // SNOTEL: 11.2mi away
    // Liftie match: not_fetched
  },
  'anthony-lakes-ski-area': {
    nwsStationId:  "OD128",
    nwsConfidence: "low",
    snotelTriplet: "1245:OR:SNTLT",
    liftieSlug:    null,
    // NWS: 16.8mi away, 3755ft elev delta
    // SNOTEL: 0.2mi away
    // Liftie match: not_fetched
  },
  'crystal-mountain-wa': {
    nwsStationId:  "TWHIT",
    nwsConfidence: "low",
    snotelTriplet: "418:WA:SNTL",
    liftieSlug:    null,
    // NWS: 20.4mi away, 2514ft elev delta
    // SNOTEL: 6.3mi away
    // Liftie match: not_fetched
  },
  'stevens-pass': {
    nwsStationId:  "SKKW1",
    nwsConfidence: "low",
    snotelTriplet: null,
    liftieSlug:    null,
    // NWS: 9.9mi away, 3817ft elev delta
    // Liftie match: not_fetched
  },
  'summit-at-snoqualmie': {
    nwsStationId:  "KSEA",
    nwsConfidence: "low",
    snotelTriplet: "1050:WA:SNTL",
    liftieSlug:    "the-summit-at-snoqualmie",
    // NWS: 0.3mi away, 2448ft elev delta
    // SNOTEL: 3.6mi away
    // Liftie match: not_fetched
  },
  'white-pass-ski-area': {
    nwsStationId:  "KYKM",
    nwsConfidence: "low",
    snotelTriplet: "778:WA:SNTL",
    liftieSlug:    "white-pass",
    // NWS: 0.1mi away, 1502ft elev delta
    // SNOTEL: 1.1mi away
    // Liftie match: not_fetched
  },
  '49-degrees-north': {
    nwsStationId:  "KGEG",
    nwsConfidence: "low",
    snotelTriplet: "778:WA:SNTL",
    liftieSlug:    "49-degrees-north",
    // NWS: 11.7mi away, 2494ft elev delta
    // Liftie match: not_fetched
  },
  'mission-ridge': {
    nwsStationId:  "KEAT",
    nwsConfidence: "medium",
    snotelTriplet: "778:WA:SNTL",
    liftieSlug:    "mission-ridge",
    // NWS: 11.9mi away, 5513ft elev delta
    // SNOTEL: 4mi away
    // Liftie match: not_fetched
  },
  'mt-baker-ski-area': {
    nwsStationId:  "KBLI",
    nwsConfidence: "low",
    snotelTriplet: "1024:WA:SNTL",
    liftieSlug:    "mt-baker",
    // NWS: 6.9mi away, 1480ft elev delta
    // SNOTEL: 12.2mi away
    // Liftie match: not_fetched
  },
  'alyeska-resort': {
    nwsStationId:  "PANC",
    nwsConfidence: "low",
    snotelTriplet: "1099:AK:SNTL",
    liftieSlug:    "alyeska",
    // NWS: 16mi away, 3844ft elev delta
    // SNOTEL: 15.2mi away
    // Liftie match: not_fetched
  },
};

// CommonJS export for use in Vercel serverless functions
if (typeof module !== 'undefined') module.exports = RESORT_SOURCES;
