// Auto-generated by get-snocountry-ids.mjs — 2026-03-31
// 250 resorts unmatched — see snocountry-id-map.json for the manual review list
// Paste this block into api/conditions.js replacing the existing ID_MAP

const ID_MAP = {

};
