/**
 * scripts/merge-sources.mjs
 *
 * Combines the three lookup JSON files with the hand-curated seed data
 * to produce the final resort-sources.js mapping file.
 *
 * Run after all three lookup scripts have completed:
 *   node scripts/find-nws-stations.mjs
 *   node scripts/find-snotel-stations.mjs
 *   node scripts/match-liftie-slugs.mjs
 *   node scripts/merge-sources.mjs   <-- this script
 *
 * Output: resort-sources.js (repo root)
 *
 * Merge priority (highest wins):
 *   1. Hand-curated overrides in resort-sources-seed.js (your manual fixes)
 *   2. Lookup script output (automated)
 *
 * Re-run this script any time you update the seed or re-run a lookup script.
 * It is non-destructive -- it reads inputs and writes one output file.
 */

import { createRequire } from 'module';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const require   = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const RESORTS    = require('../api/resorts-data.js');
const ROOT       = path.join(__dirname, '..');
const OUT_FILE   = path.join(ROOT, 'resort-sources.js');

const SNOTEL_STATES = new Set(['CO','UT','WY','MT','ID','NV','CA','OR','WA','AZ','NM','AK']);

// ─── Load a JSON lookup file if it exists ────────────────────────────────────

function loadJson(filePath, label) {
  if (!existsSync(filePath)) {
    console.warn(`  Warning: ${label} not found at ${filePath} -- skipping`);
    return [];
  }
  const data = JSON.parse(readFileSync(filePath, 'utf8'));
  console.log(`  Loaded ${data.length} entries from ${label}`);
  return data;
}

// ─── Load seed overrides if resort-sources-seed.js exists ────────────────────

function loadSeed() {
  const seedPath = path.join(ROOT, 'resort-sources-seed.js');
  if (!existsSync(seedPath)) {
    console.log('  No resort-sources-seed.js found -- using lookup data only');
    return {};
  }
  try {
    const obj   = require('../resort-sources-seed.js');
    const count = Object.keys(obj).length;
    console.log(`  Loaded ${count} seed entries from resort-sources-seed.js`);
    return obj;
  } catch (err) {
    console.warn(`  Could not load resort-sources-seed.js: ${err.message}`);
    return {};
  }
}
// ─── Build confidence label ───────────────────────────────────────────────────

function nwsConfidence(entry) {
  if (!entry || entry.error) return 'none';
  if (entry.confidence) return entry.confidence;
  const mi  = entry.distanceMiles ?? 999;
  const dft = entry.elevationDeltaFt ?? 9999;
  if (mi <= 10 && dft <= 500)  return 'high';
  if (mi <= 25 && dft <= 1200) return 'medium';
  return 'low';
}

// ─── Format a single resort entry for output ─────────────────────────────────

function formatEntry(resort, nws, snotel, liftie, seed) {
  const s = seed ?? {};

  // NWS -- seed overrides lookup
  const nwsId   = s.nwsStationId   ?? nws?.nwsStationId   ?? null;
  const nwsConf = s.nwsConfidence  ?? (nws ? nwsConfidence(nws) : 'none');

  // SNOTEL -- seed overrides lookup, null for eastern states
  const snotelId = SNOTEL_STATES.has(resort.state)
    ? (s.snotelTriplet ?? snotel?.snotelTriplet ?? null)
    : null;

  // Liftie -- seed overrides lookup
  const liftieSlug = s.liftieSlug ?? liftie?.liftieSlug ?? null;

  return {
    id:             resort.id,
    nwsStationId:   nwsId,
    nwsConfidence:  nwsConf,
    snotelTriplet:  snotelId,
    liftieSlug:     liftieSlug,
    // Diagnostic fields (strip these in production if you want a leaner file)
    _nwsDistMi:     nws?.distanceMiles    ?? null,
    _nwsElevDelta:  nws?.elevationDeltaFt ?? null,
    _snotelDistMi:  snotel?.distanceMiles ?? null,
    _liftieMatch:   liftie?.matchType     ?? null,
  };
}

// ─── Generate the JS file content ─────────────────────────────────────────────

function generateFile(entries, totalResorts) {
  const timestamp = new Date().toISOString();
  const lines = [];

  lines.push(`/**`);
  lines.push(` * resort-sources.js`);
  lines.push(` *`);
  lines.push(` * Authoritative mapping: resort ID -> external data source identifiers.`);
  lines.push(` * Generated by scripts/merge-sources.mjs -- do not edit by hand.`);
  lines.push(` * To update: run the lookup scripts and re-run merge-sources.mjs.`);
  lines.push(` * Last generated: ${timestamp}`);
  lines.push(` *`);
  lines.push(` * nwsStationId:  4-letter ICAO station code for NWS observation data`);
  lines.push(` * nwsConfidence: high/medium/low -- how closely the station matches summit elevation`);
  lines.push(` * snotelTriplet: USDA AWDB triplet e.g. "1125:UT:SNTL" -- western resorts only`);
  lines.push(` * liftieSlug:    liftie.info resort slug for lift/trail status -- null if not listed`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`const RESORT_SOURCES = {`);

  for (const entry of entries) {
    lines.push(`  '${entry.id}': {`);
    lines.push(`    nwsStationId:  ${JSON.stringify(entry.nwsStationId)},`);
    lines.push(`    nwsConfidence: ${JSON.stringify(entry.nwsConfidence)},`);
    lines.push(`    snotelTriplet: ${JSON.stringify(entry.snotelTriplet)},`);
    lines.push(`    liftieSlug:    ${JSON.stringify(entry.liftieSlug)},`);
    if (entry._nwsDistMi != null)  lines.push(`    // NWS: ${entry._nwsDistMi}mi away, ${entry._nwsElevDelta ?? '?'}ft elev delta`);
    if (entry._snotelDistMi != null) lines.push(`    // SNOTEL: ${entry._snotelDistMi}mi away`);
    if (entry._liftieMatch)          lines.push(`    // Liftie match: ${entry._liftieMatch}`);
    lines.push(`  },`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`// CommonJS export for use in Vercel serverless functions`);
  lines.push(`if (typeof module !== 'undefined') module.exports = RESORT_SOURCES;`);
  lines.push(``);

  return lines.join('\n');
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Loading data sources...');

  const nwsData    = loadJson(path.join(__dirname, 'output', 'nws-station-lookup.json'),    'NWS lookup');
  const snotelData = loadJson(path.join(__dirname, 'output', 'snotel-station-lookup.json'), 'SNOTEL lookup');
  const liftieData = loadJson(path.join(__dirname, 'output', 'liftie-slug-lookup.json'),    'Liftie lookup');
  const seed       = loadSeed();

  // Index by resort ID for O(1) lookup
  const nwsById    = Object.fromEntries(nwsData.map(r    => [r.id, r]));
  const snotelById = Object.fromEntries(snotelData.map(r => [r.id, r]));
  const liftieById = Object.fromEntries(liftieData.map(r => [r.id, r]));

  console.log(`\nMerging ${RESORTS.length} resorts...`);

  const entries = RESORTS.map(resort =>
    formatEntry(
      resort,
      nwsById[resort.id]    ?? null,
      snotelById[resort.id] ?? null,
      liftieById[resort.id] ?? null,
      seed[resort.id]       ?? null,
    )
  );

  const content = generateFile(entries, RESORTS.length);
  writeFileSync(OUT_FILE, content, 'utf8');

  // Stats
  const hasNws    = entries.filter(e => e.nwsStationId).length;
  const hasSnotel = entries.filter(e => e.snotelTriplet).length;
  const hasLiftie = entries.filter(e => e.liftieSlug).length;
  const lowNws    = entries.filter(e => e.nwsConfidence === 'low').length;

  console.log('\n--- Final resort-sources.js stats ---');
  console.log(`Total resorts:      ${entries.length}`);
  console.log(`Has NWS station:    ${hasNws}`);
  console.log(`  Low confidence:   ${lowNws}  <-- review these for scoring weight`);
  console.log(`Has SNOTEL:         ${hasSnotel}`);
  console.log(`Has Liftie slug:    ${hasLiftie}`);
  console.log(`\nOutput: ${OUT_FILE}`);
  console.log('\nDone. Review resort-sources.js, then commit.');
}

main().catch(err => { console.error(err); process.exit(1); });
